# Generated by Django 5.2.17 on 2026-09-20 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van')], max_length=16, unique=True)),
                ('fleet_size', models.PositiveIntegerField(help_text='Number of cars of this type available to rent.')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__in', ['sedan', 'suv', 'van'])), name='car_type_name_is_known')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='Pick-up time (inclusive).')),
                ('end_at', models.DateTimeField(help_text='Return time (exclusive): the car is free again from this moment.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('idempotency_key', models.CharField(help_text='Client-generated key identifying one booking attempt across retries.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rentals.cartype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'active')), fields=['car_type', 'start_at', 'end_at'], name='reservation_active_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='reservation_end_after_start'), models.UniqueConstraint(fields=('user', 'idempotency_key'), name='reservation_idempotency_key_unique_per_user'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(('cancelled_at__isnull', True), ('status', 'active')), _connector='OR'), name='reservation_cancelled_at_matches_status')],
            },
        ),
    ]
